### ISSUE TITLE
Need application services in another position in the metamodel

### ISSUE THREAD

**Issue by Laurentjg** [lfenergyarchitecturemodel/lfenergyfunctionalarchitecturemodel#87]
Some projects do have services that are not independently deployable. E.g. in FledgePower (plugins). The current metamodel does not support this kind of modelling at this moment. Proposal is to upgrade the metamodel.

**Comment by PrinceAlliander** [comment]
On 19th April a meeting was held to discuss this point. It was decided that to address the issue of differentiating between deployable and non deployable application components - a '*' could be appended to the application component. Another approach is by adding supporting text in the architecture figure itself to to clarify which components are independently deployable or otherwise. In short, it was decided for the sake of simplicity and consensus to not add additional elements to the metamodel (for now).
